spring.application.name=RealEstateTransactionSystem
spring.datasource.url=${DB_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

# Keycloak and oauth2 configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server.port=${SERVER_PORT}
jwt.auth.converter.resource-id=${RESOURCE_ID}
jwt.auth.converter.principle-attribute=${PRINCIPLE_ATTRIBUTE}
#keyloak.client-id=${CLIENT_ID}
#keyloak.roles.seller-id=${SELLER_ID}
#keyloak.roles.broker-id=${BROKER_ID}
#keyloak.roles.buyer-id=${BUYER_ID}
#keyloak.user.get-user-id-url = ${GET_USER_ID_URL}
#keyloak.user.add-user-url = ${ADD_USER_URL}

# show sql commands
spring.jpa.show-sql=true
# show sql queries
spring.jpa.properties.hibernate.format_sql=true
# ddl (create, alter, truncate)
spring.jpa.generate-ddl=true
spring.jpa.open-in-view=true
# update is necessary for relations
spring.jpa.hibernate.ddl-auto=update
# Error tracing
server.error.include-message=always
server.error.include-stacktrace=always