spring.application.name=RealEstateTransactionSystem

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

# Keycloak and oauth2 configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/RealEstateSystem
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server.port=${SERVER_PORT}
# JWT
keycloak.resource-id=${RESOURCE_ID}
keycloak.jwt.principle-attribute=${PRINCIPLE_ATTRIBUTE}

# Keycloak URLs
keycloak.urls.add-user=${ADD_USER_URL}
keycloak.urls.get-user=${GET_USER_KEYCLOAK_ID_URL}
keycloak.urls.get-token=${GET_USER_TOKEN_URL}
keycloak.urls.get-role-id=${GET_KEYCLOAK_ROLE_ID_URL}
keycloak.urls.get-client-id=${GET_CLIENT_ID_URL}
keycloak.urls.assign-role=${ASSIGN_KEYCLOAK_ROLE_URL}

# Keycloak client
keycloak.client.id=${ADMIN_CLIENT_ID}
keycloak.client.secret=${CLIENT_SECRET}

# Keycloak base URL (optional if you want to keep it)
keycloak.base-url=${KEYCLOAK_BASE_URL}



# show sql commands
spring.jpa.show-sql=false
# show sql queries
spring.jpa.properties.hibernate.format_sql=false
# ddl (create, alter, truncate)
spring.jpa.generate-ddl=true
spring.jpa.open-in-view=true


spring.jpa.hibernate.ddl-auto=none
# Error tracing
server.error.include-message=always
server.error.include-stacktrace=never

logging.file.name=realestate.log

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Email
rabbitmq.exchange-name=${RABBITMQ_EXCHANGE_NAME}
rabbitmq.email-queue.queue-name=${RABBITMQ_EMAIL_QUEUE_NAME}
rabbitmq.email-queue.routing-key-name=${RABBITMQ_EMAIL_ROUTING_KEY_NAME}

# Property
rabbitmq.property-queue.queue-name = ${RABBITMQ_PROPERTY_QUEUE_NAME}
rabbitmq.property-queue.routing-key-name = ${RABBITMQ_PROPERTY_ROUTING_KEY_NAME}






logging.include-application-name=false