spring.application.name=RealEstateTransactionSystem
spring.datasource.url=${DB_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

# Keycloak and oauth2 configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_BASE_URL}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server.port=${SERVER_PORT}
resource-id=${RESOURCE_ID}
jwt.auth.converter.principle-attribute=${PRINCIPLE_ATTRIBUTE}

# Keycloak URLs
add-user-url = ${ADD_USER_URL}
get-user-keycloak-url = ${GET_USER_KEYCLOAK_ID_URL}
get-user-token-url = ${GET_USER_TOKEN_URL}
get-role-id-url = ${GET_KEYCLOAK_ROLE_ID_URL}
get-client-id-url = ${GET_CLIENT_ID_URL}
assign-role-keycloak-url = ${ASSIGN_KEYCLOAK_ROLE_URL}
client-secret = ${CLIENT_SECRET}
admin-client-id = ${ADMIN_CLIENT_ID}
keycloak-base-url = ${KEYCLOAK_BASE_URL}
# show sql commands
spring.jpa.show-sql=true
# show sql queries
spring.jpa.properties.hibernate.format_sql=true
# ddl (create, alter, truncate)
spring.jpa.generate-ddl=true
spring.jpa.open-in-view=true
# update is necessary for relations
spring.jpa.hibernate.ddl-auto=update
# Error tracing
server.error.include-message=always
server.error.include-stacktrace=always